version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - dataframe
  - dotenv
  - dtype
  - Iltalehti
  - Instrumentor
  - Klikkikuri
  - markdownify
  - opentelemetry
  - platformdirs
  - pydantic
ignoreWords:
  - Meri
  - Valas
  - structlog
import: []
